### ISSUE TITLE
Reconsider "Donate"

### ISSUE THREAD

**Issue by kemitchell** [commonform/new-publisher-guide#1]
@tbrooke mentioned that "donate" feels a bit strange. I agree.

Wonder whether we might use "file", "share", or some other word with less confusing connotations.

@anseljh, any ideas?

**Comment by anseljh** [comment]
How about just "add", and delete the modifier when it's unnecessary?

So:

> Donating a form means giving Common Form's server a copy of the form for storage. Each donated form, and each part of every donated form, is stored by hash.

becomes

> Adding a form means giving Common Form's server a copy of the form for storage. Each added form, and each part of every added form, is stored by hash.

and

> Anyone that asks for a donated form by hash gets a copy.

becomes

> Anyone that asks for a form by hash gets a copy.

and

> Nor does the server index donated forms in any way.

becomes

> Nor does the server index forms in any way.

**Comment by kemitchell** [comment]
What should the button on the website say? "Add Form"?

**Comment by tbrooke** [comment]
I like add - it seems simpler
